"""Filesystem checkpoints — snapshot/restore files before mutating tools.

Save points live under ``data/checkpoints/{sessionId}/{checkpointId}/``.
Each checkpoint stores a ``manifest.json`` and copies of file contents
(relative paths under the session workspace when possible).
"""

from __future__ import annotations

import json
import logging
import shutil
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from app.json_narrowing import as_list, as_str
from app.services.sandbox.paths import is_within_root

logger = logging.getLogger('workbench.checkpoints')

MAX_FILE_BYTES = 2 * 1024 * 1024  # 2 MiB per file
MAX_CHECKPOINTS_PER_SESSION = 20


def _data_root() -> Path:
    try:
        from app.lib.paths import dataDir

        return Path(dataDir())
    except Exception:
        from app.config import settings

        return Path(settings.dataDir)


def _safe_segment(value: str) -> str | None:
    """A single path SEGMENT, or None if the value is not one.

    Both `sessionId` and `checkpointId` reach `_data_root()/checkpoints/<sid>/<ck>`
    straight from the caller, and pathlib happily honours a separator inside
    what looks like one segment: `..%5C..%5C<dir>` decodes to a backslash and
    walks out of the checkpoint store entirely, so a crafted id could read a
    `manifest.json` from anywhere on disk. That is the same shape as the
    observations route, one layer down.

    The ids are generated by this module, so a real one is always a single
    safe segment — anything else is either a bug or an attack, and returning
    None lets the callers fail closed without duplicating the rule.

    A backslash is rejected on every platform, not just Windows: a checkpoint
    directory is never created with one, so a value carrying it cannot be a
    legitimate id, and accepting it on POSIX would only hide the bug until
    someone ran on Windows.
    """
    if not value or value in ('.', '..'):
        return None
    if '/' in value or '\\' in value or '\x00' in value:
        return None
    if ':' in value:  # drive-absolute `C:` and NTFS ADS `file.png:stream`
        return None
    return value


def _session_dir(session_id: str) -> Path | None:
    """The checkpoint directory for a session, or None for an unsafe id."""
    safe = _safe_segment(session_id)
    if safe is None:
        return None
    return _data_root() / 'checkpoints' / safe


def _checkpoint_dir(session_id: str, checkpoint_id: str) -> Path | None:
    """One checkpoint's directory, contained inside the store.

    Containment is checked on the RESOLVED path as well as the segments, so a
    symlink planted inside the store cannot redirect a read either — the
    segment check alone would accept `ck-1` and let the filesystem do the rest.
    """
    session_dir = _session_dir(session_id)
    if session_dir is None:
        return None
    safe_ck = _safe_segment(checkpoint_id)
    if safe_ck is None:
        return None
    try:
        root = (_data_root() / 'checkpoints').resolve()
        candidate = (session_dir / safe_ck).resolve(strict=False)
    except OSError:
        return None
    if not is_within_root(candidate, root):
        return None
    return candidate


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _paths_from_tool_args(tool_name: str, args: dict[str, Any] | None) -> list[str]:
    args = args or {}
    name = (tool_name or '').lower()
    paths: list[str] = []
    for key in ('path', 'file_path', 'filePath', 'file', 'target', 'destination', 'src', 'dest'):
        v = as_str(args.get(key))
        if v:
            paths.append(v)
    # apply_patch / multi-file style
    for key in ('paths', 'files'):
        raw = args.get(key)
        if isinstance(raw, list):
            for item in raw:
                if isinstance(item, str):
                    paths.append(item)
                elif isinstance(item, dict):
                    p = as_str(item.get('path'))
                    if p:
                        paths.append(p)
    if any(m in name for m in ('bash', 'shell', 'command', 'exec')):
        # Shell may touch anything — no path snapshot unless cwd file is known
        pass
    return paths


def _resolve_under_workspace(path_str: str, workspace: str) -> Path | None:
    """Resolve a model-supplied path under the rules the file tools already enforce.

    A checkpoint is a COPY, and it is taken BEFORE the file tool is dispatched:
    ``create_checkpoint_for_tool`` runs on the raw ``toolInput`` path, so the
    tool's own refusal (``bind_path`` inside ``write_file`` and friends) always
    lands a moment too late. The concrete exploit was
    ``write_file(path="C:\\Users\\<u>\\.ssh\\id_rsa")`` — correctly refused
    downstream, but only after ``shutil.copy2`` had already staged the private
    key under ``data/checkpoints/`` with its absolute path recorded in
    ``manifest.json``, from where a later read could collect it.
    ``providers.json`` took the same route. The old fallback here
    ("allow an absolute path outside the workspace when it happens to exist")
    is what let both through; it is gone.

    What is left are the two guards ``bind_path`` itself applies, in the same
    order: hardline credential rules FIRST — a private key or an API-key store
    is not save-point material in ANY sandbox mode, Full Access included — then
    workspace containment. Both hardline modes are consulted because a
    checkpoint does two things to the path at once: it reads the file into a
    copy, and it tracks a file the model is about to write.
    """
    from app.services.sandbox.hardline import check_hardline_path
    from app.services.sandbox.paths import is_within_root, resolve_workspace_root

    try:
        candidate = Path(path_str).expanduser()
        root = resolve_workspace_root(workspace)
        if not candidate.is_absolute() and root is not None:
            candidate = root / candidate
        resolved = candidate.resolve(strict=False)
    except OSError:
        return None

    for for_write in (False, True):
        denial = check_hardline_path(str(resolved), for_write=for_write)
        if denial:
            logger.warning('checkpoint refused protected path: %s', denial)
            return None

    if root is None:
        # No workspace is bound, so there is no containment anchor. A save
        # point only ever exists to restore a WRITE, and `bind_path` answers
        # a workspace-less write the same way: the system temp area only.
        import tempfile

        try:
            temp_root = Path(tempfile.gettempdir()).resolve()
        except OSError:
            return None
        return resolved if is_within_root(resolved, temp_root) else None
    return resolved if is_within_root(resolved, root) else None


def create_checkpoint(
    session_id: str,
    workspace_path: str = '',
    paths: list[str] | None = None,
    tool_name: str = '',
    label: str = '',
    reason: str = 'mutation',
) -> dict[str, Any] | None:
    """Snapshot existing files that will be changed. Returns checkpoint meta or None."""
    if not session_id:
        return None
    resolved: list[Path] = []
    for raw in paths or []:
        rp = _resolve_under_workspace(raw, workspace_path)
        if rp is not None and rp.is_file():
            try:
                if rp.stat().st_size <= MAX_FILE_BYTES:
                    resolved.append(rp)
            except OSError:
                continue
    # Always create a checkpoint record even if no files existed yet (new file write)
    # so restore can delete newly created files tracked in manifest.
    ck_id = f'cp_{uuid.uuid4().hex[:12]}'
    session_dir = _session_dir(session_id)
    if session_dir is None:
        return None
    base = session_dir / ck_id
    files_dir = base / 'files'
    try:
        files_dir.mkdir(parents=True, exist_ok=True)
    except OSError:
        logger.exception('checkpoint mkdir failed')
        return None

    entries: list[dict[str, Any]] = []
    ws = Path(workspace_path).resolve() if workspace_path else None
    for src in resolved:
        try:
            rel = src.name
            if ws is not None:
                try:
                    rel = str(src.relative_to(ws)).replace('\\', '/')
                except ValueError:
                    rel = src.name
            # Flatten nested paths safely under files/
            dest = files_dir / rel.replace('..', '_')
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)
            entries.append(
                {
                    'path': str(src),
                    'rel': rel,
                    'existed': True,
                    'size': src.stat().st_size,
                }
            )
        except OSError:
            logger.debug('skip snapshot %s', src, exc_info=True)

    # Track intended paths that did not exist (for delete-on-restore of new files)
    for raw in paths or []:
        rp = _resolve_under_workspace(raw, workspace_path)
        if rp is None:
            continue
        if any(e['path'] == str(rp) for e in entries):
            continue
        rel = rp.name
        if ws is not None:
            try:
                rel = str(rp.relative_to(ws)).replace('\\', '/')
            except ValueError:
                pass
        entries.append({'path': str(rp), 'rel': rel, 'existed': False, 'size': 0})

    meta: dict[str, Any] = {
        'id': ck_id,
        'sessionId': session_id,
        'createdAt': _now(),
        'label': label or (f'Before {tool_name}' if tool_name else 'Save point'),
        'reason': reason,
        'toolName': tool_name,
        'workspacePath': workspace_path,
        'fileCount': len(entries),
        'files': entries,
    }
    try:
        (base / 'manifest.json').write_text(json.dumps(meta, indent=2), encoding='utf-8')
    except OSError:
        logger.exception('checkpoint manifest write failed')
        shutil.rmtree(base, ignore_errors=True)
        return None

    _prune_old(session_id)
    return meta


def create_checkpoint_for_tool(
    session_id: str,
    workspace_path: str,
    tool_name: str,
    args: dict[str, Any] | None,
) -> dict[str, Any] | None:
    paths = _paths_from_tool_args(tool_name, args)
    if not paths and not any(
        m in (tool_name or '').lower()
        for m in ('write', 'edit', 'delete', 'remove', 'patch', 'str_replace', 'create')
    ):
        return None
    return create_checkpoint(
        session_id,
        workspace_path=workspace_path,
        paths=paths,
        tool_name=tool_name,
        reason='before_mutation',
    )


def list_checkpoints(session_id: str) -> list[dict[str, Any]]:
    root = _session_dir(session_id)
    if root is None or not root.is_dir():
        return []
    out: list[dict[str, Any]] = []
    for child in sorted(root.iterdir(), reverse=True):
        man = child / 'manifest.json'
        if not man.is_file():
            continue
        try:
            data = json.loads(man.read_text(encoding='utf-8'))
            if isinstance(data, dict):
                # Drop full file content listing for list view size
                slim = {k: v for k, v in data.items() if k != 'files'}
                slim['fileCount'] = data.get('fileCount', len(as_list(data.get('files'))))
                out.append(slim)
        except (OSError, json.JSONDecodeError):
            continue
    return out


def get_checkpoint(session_id: str, checkpoint_id: str) -> dict[str, Any] | None:
    base = _checkpoint_dir(session_id, checkpoint_id)
    if base is None:
        return None
    man = base / 'manifest.json'
    if not man.is_file():
        return None
    try:
        data = json.loads(man.read_text(encoding='utf-8'))
        return data if isinstance(data, dict) else None
    except (OSError, json.JSONDecodeError):
        return None


def _snapshot_source(files_dir: Path, rel: str) -> Path | None:
    """Resolve a manifest ``rel`` to a staged copy INSIDE this checkpoint's ``files/``.

    ``rel`` is manifest data and is not trusted either: joined as
    ``files_dir / rel``, an absolute value REPLACES the whole path, so a
    planted manifest would hand ``copy2`` any readable file on the machine to
    splatter into the workspace — past every check on the target. Containment
    is measured against ``files_dir`` with the same ``is_within_root`` the
    workspace gate uses; only the root differs.
    """
    from app.services.sandbox.paths import is_within_root

    for candidate in (files_dir / rel.replace('..', '_'), files_dir / Path(rel).name):
        try:
            resolved = candidate.resolve(strict=False)
        except OSError:
            continue
        if is_within_root(resolved, files_dir) and resolved.is_file():
            return resolved
    return None


def restore_checkpoint(session_id: str, checkpoint_id: str) -> dict[str, Any]:
    """Restore files from a checkpoint. Deletes files that did not exist at snapshot time."""
    meta = get_checkpoint(session_id, checkpoint_id)
    if not meta:
        return {'ok': False, 'error': 'Checkpoint not found'}
    base = _checkpoint_dir(session_id, checkpoint_id)
    if base is None:
        return {'ok': False, 'error': 'Checkpoint not found'}
    files_dir = base / 'files'
    # A manifest is a FILE ON DISK, so "we wrote it" is not a reason to trust
    # it on the way out. Every target below is re-run through the same guard
    # the create side used, against the workspace the manifest itself names —
    # a manifest edited or planted after the fact cannot redirect a restore
    # at a protected path or outside the workspace.
    workspace = as_str(meta.get('workspacePath')) or ''
    restored = 0
    deleted = 0
    errors: list[str] = []
    for entry in as_list(meta.get('files')):
        if not isinstance(entry, dict):
            continue
        path_str = as_str(entry.get('path'))
        if not path_str:
            continue
        rel = as_str(entry.get('rel')) or Path(path_str).name
        existed = bool(entry.get('existed'))
        target = _resolve_under_workspace(path_str, workspace)
        if target is None:
            errors.append(f'refused (outside workspace or hardline protected): {path_str}')
            continue
        try:
            if existed:
                src = _snapshot_source(files_dir, rel)
                if src is None:
                    errors.append(f'missing snapshot for {path_str}')
                    continue
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, target)
                restored += 1
            else:
                if target.is_file():
                    target.unlink()
                    deleted += 1
        except OSError as exc:
            errors.append(f'{path_str}: {exc}')
    return {
        'ok': True,
        'checkpointId': checkpoint_id,
        'restored': restored,
        'deleted': deleted,
        'errors': errors,
        'label': meta.get('label'),
        'message': (
            f'Restored save point “{meta.get("label")}” '
            f'({restored} file(s) restored, {deleted} new file(s) removed).'
        ),
    }


def _prune_old(session_id: str) -> None:
    root = _session_dir(session_id)
    if root is None or not root.is_dir():
        return
    dirs = sorted(
        [d for d in root.iterdir() if d.is_dir() and (d / 'manifest.json').is_file()],
        key=lambda d: d.stat().st_mtime,
        reverse=True,
    )
    for old in dirs[MAX_CHECKPOINTS_PER_SESSION:]:
        shutil.rmtree(old, ignore_errors=True)


# camelCase aliases
createCheckpoint = create_checkpoint
createCheckpointForTool = create_checkpoint_for_tool
listCheckpoints = list_checkpoints
getCheckpoint = get_checkpoint
restoreCheckpoint = restore_checkpoint
