"""Derived markdown mirrors for memory, system prompt, and skills.

SQLite is source of truth — files are versioned views via atomic writes,
debounced and secrets-scrubbed. Flag ``auxiliary.memory_md_export`` mirrors
``session_json_export`` (docs/CONFIGURATION.md:154).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from app.json_narrowing import as_str

# 30s debounce per scope
_last_export: dict[str, float] = {}


def _enabled() -> bool:
    if os.environ.get("AUGUST_MEMORY_MD_EXPORT", "").strip().lower() in ("0", "false", "no"):
        return False
    try:
        from app.services.cognitive_config import get_features
        feat = get_features()
        # auxiliary.memory_md_export defaults on; absent -> on
        if isinstance(feat, dict) and "memory_md_export" in feat:
            return bool(feat.get("memory_md_export"))
    except Exception:
        pass
    return True


def _data_dir() -> Path:
    try:
        from app.lib.paths import dataPath
        return Path(str(dataPath()))
    except Exception:
        return Path("data")


def _aug_dir(workspace_path: str | None = None) -> Path:
    # Per-workspace .aug when workspace given, else data/.aug
    if workspace_path:
        try:
            return Path(workspace_path) / ".aug"
        except Exception:
            pass
    return _data_dir() / ".aug"


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def _scrub(text: str) -> str:
    try:
        from app.services.memory.memory_scrubber import find_secrets
        if find_secrets(text):
            return "[redacted: potential secret]"
    except Exception:
        pass
    return text


def export_memory_markdown(folder_id: str = "", origin: str = "all") -> Path | None:
    """Export a memory view to data/memory.md or data/memory/<folder_id>.md."""
    if not _enabled():
        return None
    try:
        from app.services.memory.auto_memory import list_all_auto_memories, present_memory_fields
    except Exception:
        return None
    folder_id = (folder_id or "").strip()
    origin = (origin or "all").strip().lower() or "all"
    # Path-traversal guard: folder ids are UI-generated slugs ("folder_xxx").
    # Anything carrying separators or dot-segments would escape data/memory/.
    # Dot-leading ids (".", "..hidden") are also rejected — they never occur
    # as real folder ids and degenerate filenames ("..md") invite trouble.
    if folder_id and (
        "/"
        in folder_id
        or "\\" in folder_id
        or ".." in folder_id
        or folder_id.startswith(".")
        or os.path.basename(folder_id) != folder_id
    ):
        return None
    try:
        items = list_all_auto_memories(origin=origin, folder_id=folder_id, include_telemetry=False)
    except Exception:
        items = []
    # Scrub
    for it in items:
        it["content"] = _scrub(str(it.get("content") or it.get("summary") or ""))
    # Group
    areas: list[dict[str, Any]] = []
    topics: list[dict[str, Any]] = []
    episodes: list[dict[str, Any]] = []
    for it in items:
        cat = str(it.get("category") or "auto").lower()
        key = str(it.get("key") or "")
        if key.startswith("episode_") or key.startswith("conv_summary_"):
            episodes.append(it)
        elif cat in ("correction", "learning", "preference", "user"):
            areas.append(it)
        else:
            topics.append(it)
    title = f"Memory — {origin}" + (f" / {folder_id}" if folder_id else " (global)")
    lines: list[str] = [f"# {title}", ""]
    if folder_id:
        lines += [f"> Project: `{folder_id}` — `source_session_id → sessions.folder_id` join.", ""]
    else:
        lines += ["> Global view — all projects. Use `?folder_id=` for per-project.", ""]
    # Frontmatter-like summary table header
    lines += [f"_Generated by markdown_export — {len(items)} items — SQLite is source of truth._", ""]
    def _render_section(name: str, rows: list[dict[str, Any]]) -> None:
        if not rows:
            return
        lines.append(f"## {name}")
        lines.append("")
        for it in rows:
            fields = present_memory_fields(str(it.get("key") or ""), it.get("content"), str(it.get("category") or "auto"))
            title2 = str(fields.get("title") or it.get("title") or it.get("key") or "Memory")
            summary = str(fields.get("summary") or it.get("summary") or "")
            section = str(it.get("section") or fields.get("section") or "")
            graph = it.get("graph") if isinstance(it.get("graph"), dict) else {}
            rc = graph.get("relationCount", 0) if graph else 0
            oc = graph.get("observationCount", 0) if graph else 0
            conf = it.get("confidence")
            exp = it.get("expiresAt") or it.get("expires_at")
            lines.append(f"### {title2}")
            lines.append("")
            lines.append(f"- id: `{it.get('id')}` · key: `{it.get('key')}` · category: `{it.get('category')}` · section: `{section}`")
            pinned = " pinned" if it.get("pinned") else ""
            lines.append(f"- importance: `{it.get('importance')}` · confidence: `{conf}` · source: `{it.get('source')}`{pinned}")
            if exp:
                lines.append(f"- expires_at: `{exp}` · ttl_days: `{it.get('ttlDays', it.get('ttl_days'))}`")
            if rc or oc:
                lines.append(f"- graph: relations `{rc}` · observations `{oc}`")
            if it.get("sourceSessionId") or it.get("source_session_id"):
                lines.append(f"- provenance: session `{it.get('sourceSessionId') or it.get('source_session_id')}` → folder `{it.get('folderId') or it.get('folder_id') or folder_id or '-'}`")
            if summary:
                lines.append(f"- summary: {summary}")
            content = it.get("content")
            if isinstance(content, str) and content and content != summary:
                preview = content[:600].replace("\n", " ")
                lines.append(f"  > {preview}")
            lines.append("")
    _render_section("Areas", areas)
    _render_section("Topics", topics)
    _render_section("Episodes", episodes)
    if not items:
        lines += ["_No memories in this view._", ""]
    content = "\n".join(lines)
    if folder_id:
        dest = _data_dir() / "memory" / f"{folder_id}.md"
    else:
        dest = _data_dir() / "memory.md"
    try:
        _atomic_write(dest, content)
        return dest
    except Exception:
        return None


def export_system_prompt_markdown(
    session: dict[str, Any] | None = None,
    *,
    tiers: tuple[str, str, str] | None = None,
) -> Path | None:
    """Write the assembled 3-tier prompt as markdown.

    ``tiers`` lets callers that already built Tier1/2/3 (e.g. the workbench
    prompt rebuild path) pass them in so the mirror never causes redundant
    tier builds or defeats the T1/T2 prompt cache.
    """
    if not _enabled():
        return None
    sess = session or {}
    if tiers is not None:
        t1, t2, t3 = (str(t or "") for t in tiers)
    else:
        try:
            from app.services.memory.context_builder import buildTier1, buildTier2, buildTier3

            t1 = buildTier1(sess)
            t2 = buildTier2(sess)
            t3 = buildTier3(sess)
        except Exception:
            return None
    sid = as_str(sess.get("id") or sess.get("sessionId") or "")
    fid = as_str(sess.get("folderId") or sess.get("folder_id") or "")
    lines = [f"# System Prompt — {sid or 'global'}", "", f"_Generated at buildSystemPrompt — folder `{fid or '-'}` — 3 tiers._", ""]
    lines += ["## Tier 1 — Identity", "", "```xml", t1 or "(empty)", "```", ""]
    lines += ["## Tier 2 — Experience", "", "```xml", t2 or "(empty)", "```", ""]
    lines += ["## Tier 3 — Runtime", "", "```xml", t3 or "(empty)", "```", ""]
    content = "\n".join(lines)
    # Global + per-session
    global_dest = _data_dir() / "system-prompt.md"
    try:
        _atomic_write(global_dest, content)
    except Exception:
        pass
    if sid:
        per = _aug_dir(as_str(sess.get("workspacePath") or sess.get("workspace_path") or "")) / "system-prompt" / f"{sid}.md"
        try:
            _atomic_write(per, content)
            return per
        except Exception:
            pass
    return global_dest


def export_skills_markdown() -> Path | None:
    if not _enabled():
        return None
    try:
        from app.services import skill_service
        items = skill_service.catalogue()
    except Exception:
        items = []
    lines = ["# Skills catalogue", "", f"_Generated — {len(items)} skills — SQLite + SKILL.md are source of truth._", ""]
    lines += ["| name | description | trigger | category | updatedAt |", "|---|---|---|---|---|"]
    for it in items[:200]:
        name = str(it.get("name") or "")
        desc = str(it.get("description") or "").replace("|", "\\|")[:80]
        trig = str(it.get("trigger") or "").replace("|", "\\|")[:40]
        cat = str(it.get("category") or "")
        upd = str(it.get("updatedAt") or it.get("updated_at") or "")
        lines.append(f"| {name} | {desc} | {trig} | {cat} | {upd} |")
    content = "\n".join(lines) + "\n"
    dest = _data_dir() / "skills.md"
    try:
        _atomic_write(dest, content)
        return dest
    except Exception:
        return None


def debounced_export_memory(folder_id: str = "", origin: str = "all", delay_s: float = 2.0) -> None:
    import threading
    import time
    key = f"mem:{folder_id}:{origin}"
    now = time.monotonic()
    last = _last_export.get(key, 0)
    if now - last < delay_s:
        return
    _last_export[key] = now
    def _do():
        try:
            export_memory_markdown(folder_id=folder_id, origin=origin)
        except Exception:
            pass
    threading.Thread(target=_do, daemon=True).start()
