[mypy]
python_version = 3.12
mypy_path = app
show_column_numbers = True
show_error_codes = True
pretty = True
exclude = (?x)(^app/scripts/.*\.py$)

[mypy-app.scripts.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True

[mypy-psutil]
ignore_missing_imports = True
[mypy-pyautogui]
ignore_missing_imports = True
[mypy-pygetwindow]
ignore_missing_imports = True
[mypy-pywinpty]
ignore_missing_imports = True
[mypy-watchdog.*]
ignore_missing_imports = True
[mypy-ddgs]
ignore_missing_imports = True
[mypy-playwright.*]
ignore_missing_imports = True
[mypy-xlsx]
ignore_missing_imports = True
[mypy-mammoth]
ignore_missing_imports = True
[mypy-katex]
ignore_missing_imports = True
[mypy-pdfjs_dist]
ignore_missing_imports = True

[mypy-aiofiles]
ignore_missing_imports = True
[mypy-anthropic]
ignore_missing_imports = True
[mypy-tiktoken]
ignore_missing_imports = True
[mypy-tokenizers]
ignore_missing_imports = True
[mypy-boto3]
ignore_missing_imports = True
[mypy-sentence_transformers]
ignore_missing_imports = True
[mypy-slack_sdk.*]
ignore_missing_imports = True
[mypy-discord.*]
ignore_missing_imports = True
