const ALIASES = {
  'opencode': 'opencode-go',
  'opencode-zen': 'opencode-zen',
  'opencode-go': 'opencode-go',
  'zen': 'opencode-zen',
  'go': 'opencode-go',
  'kilocode': 'kilo',
  'kilo': 'kilo',
  'openrouter': 'openrouter',
  'nvidia': 'nvidia',
  'nvidia-nim': 'nvidia',
  'nim': 'nvidia',
  'minimax': 'minimax',
  'minimax-global': 'minimax',
  'minimax-cn': 'minimax-cn',
  'anthropic': 'anthropic',
  'claude': 'anthropic',
  'openai': 'openai-api',
  'gpt': 'openai-api',
  'codex': 'openai-codex',
  'gemini': 'gemini',
  'google': 'gemini',
  'deepseek': 'deepseek',
  'xai': 'xai',
  'grok': 'xai',
  'copilot': 'copilot',
  'github-copilot': 'copilot',
  'ollama': 'custom',
  'vllm': 'custom',
  'local': 'custom',
  'custom': 'custom',
  'bedrock': 'bedrock',
  'aws': 'bedrock',
  'azure': 'azure-foundry',
  'huggingface': 'huggingface',
  'hf': 'huggingface',
  'novita': 'novita',
  'kimi': 'kimi-coding',
  'moonshot': 'kimi-coding',
  'qwen': 'alibaba',
  'alibaba': 'alibaba',
  'stepfun': 'stepfun',
  'arcee': 'arcee',
  'nous': 'nous',
  'gmi': 'gmi',
  'gmi-cloud': 'gmi',
  'zai': 'zai',
  'glm': 'zai',
  'zhipu': 'zai',
  'xiaomi': 'xiaomi',
  'mimo': 'xiaomi',
  'ai-gateway': 'ai-gateway',
  'ollama-cloud': 'ollama-cloud',
  'cline': 'cline',
  'cline-ai': 'cline',
};

function normalizeProvider(name) {
  if (!name) return null;
  const lower = name.trim().toLowerCase();
  return ALIASES[lower] || lower;
}

module.exports = { ALIASES, normalizeProvider };
