"""Bundled-skills snapshot parity (Part 17 Phase 0, 2026-08-29).

Ship bug: the Tauri resources snapshot
(frontend/desktop/src-tauri/resources/skills/) held only 4 of 6 bundled
skills — hdl-fpga and tutor were missing, so packaged installs shipped
without them. The snapshot is regenerated by
``node scripts/prepare-desktop-backend.mjs`` (which the release pipeline
always runs), but nothing guarded the *content* parity — a missing re-run,
a half-written copy, or a filter bug would ship silently.

This test pins two contracts:
1. Repo side — every directory under ``skills/`` is a bundled skill with a
   parseable SKILL.md (guards the source the snapshot is built from).
2. Snapshot side — when the staged snapshot exists, its directory set must
   EQUAL the bundled set. The snapshot is gitignored and built on demand, so
   a fresh clone has no snapshot — that case skips rather than fails.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from app.services import skill_service

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_BUNDLED = _REPO_ROOT / 'skills'
_SNAPSHOT = _REPO_ROOT / 'frontend' / 'desktop' / 'src-tauri' / 'resources' / 'skills'


@pytest.fixture()
def freshSkillState():
    skill_service._bust_prompt_skills_cache()
    skill_service._flat_migrate_done = True  # skip repo-root flat migration scan
    yield
    skill_service._bust_prompt_skills_cache()


def _bundledNames() -> set[str]:
    """Skill directory names in the repo bundled root (skips non-dirs)."""
    if not _BUNDLED.is_dir():
        return set()
    return {e.name for e in _BUNDLED.iterdir() if e.is_dir() and (e / 'SKILL.md').exists()}


def test_bundled_root_has_skills():
    """Sanity: the bundled root exists and holds the six shipped skills."""
    names = _bundledNames()
    assert names, 'repo skills/ root is empty or missing — bundled skills lost'
    # The 2026-08-29 drift: these two were missing from the snapshot.
    assert {'august-harness', 'august-tools', 'charts', 'circuit-sim', 'hdl-fpga', 'tutor'} <= names


def test_bundled_skills_parse(freshSkillState):
    """Every repo skill parses through the real discovery path."""
    for name in sorted(_bundledNames()):
        skill = skill_service.get(name)
        assert skill is not None, f'bundled skill {name} failed to parse/discover'
        assert skill.get('enabled') is True, f'bundled skill {name} is disabled at birth'


def test_snapshot_dir_names_equal_bundled():
    """Snapshot directory set must equal the bundled set (drift guard).

    Skips on fresh clones (snapshot is a build artifact, gitignored); fails
    when a snapshot EXISTS and has drifted from skills/ — missing dirs mean
    the packaged app won't ship those skills, extra dirs mean the snapshot
    carries something the repo no longer endorses.
    """
    if not _SNAPSHOT.is_dir():
        pytest.skip('resources/skills snapshot not built yet (run prepare-desktop-backend)')
    snapNames = {e.name for e in _SNAPSHOT.iterdir() if e.is_dir()}
    bundleNames = _bundledNames()
    assert snapNames == bundleNames, (
        'bundled-skills snapshot drift: '
        f'missing from snapshot={sorted(bundleNames - snapNames)} '
        f'extra in snapshot={sorted(snapNames - bundleNames)} '
        '(re-run: node scripts/prepare-desktop-backend.mjs)'
    )


def test_snapshot_skill_md_content_matches(freshSkillState):
    """Deeper than names: each snapshotted SKILL.md must byte-match the repo.

    Catches a stale snapshot where a skill was edited in skills/ but the
    snapshot still holds the old body (names equal, content drifted).
    """
    if not _SNAPSHOT.is_dir():
        pytest.skip('resources/skills snapshot not built yet (run prepare-desktop-backend)')
    for name in sorted(_bundledNames()):
        snap = _SNAPSHOT / name / 'SKILL.md'
        src = _BUNDLED / name / 'SKILL.md'
        assert snap.exists(), f'snapshot missing SKILL.md for {name}'
        assert snap.read_text('utf-8') == src.read_text('utf-8'), (
            f'snapshot SKILL.md for {name} differs from skills/{name}/SKILL.md '
            '(re-run: node scripts/prepare-desktop-backend.mjs)'
        )


def test_packaged_resolution_sees_all_bundled_skills(freshSkillState, monkeypatch, tmp_path):
    """The packaged-app skill resolution path must discover the full set.

    In an installed build, backend.rs copies the staged snapshot to
    {appData}/backend-runtime/skills and skill_service resolves SKILLS_DIR
    to <runtime>/skills. Point SKILLS_DIR at a copy of the SNAPSHOT (when
    present, else the repo root — same contract the snapshot must satisfy)
    and assert every bundled skill is discoverable + loadable through it.
    """
    src_root = _SNAPSHOT if _SNAPSHOT.is_dir() else _BUNDLED
    packaged = tmp_path / 'runtime' / 'skills'
    packaged.mkdir(parents=True)
    for entry in src_root.iterdir():
        if entry.is_dir():
            target = packaged / entry.name
            target.mkdir()
            (target / 'SKILL.md').write_text((entry / 'SKILL.md').read_text('utf-8'), 'utf-8')
    monkeypatch.setattr(skill_service, 'SKILLS_DIR', packaged)
    skill_service._bust_prompt_skills_cache()
    try:
        names = {s['name'] for s in skill_service.list_all() if not s.get('created_by')}
        bundleNames = _bundledNames()
        assert bundleNames <= names, (
            f'packaged layout lost skills: {sorted(bundleNames - names)}'
        )
    finally:
        monkeypatch.undo()
        skill_service._bust_prompt_skills_cache()
